# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30c55b4e15057bc99ae3313ac6faec9b0c43169071b10e94ae31b07d7670ba8a8d1e0c40dc76fcc275962c3f175b85b7e9626c3162b148e7b2192cf83a8cff9b

test:
  secret_key_base: b38037358217bf2ddad07f87655290a402582baa4f7d26c2b13b655d3403464035eeb792c2ef4f23b0d362fa1f45d90b6720451b9cf614a4d1d9e2c9c8c02e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
